apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodb-backup
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mongodump
            image: mongo:latest
            command:
            - sh
            - -c
            - |
              
              mongodump --host=mongodb-service --port=27017 --out=/backup/$(date +\%Y-\%m-\%dT\%H-\%M-\%S)
              #ajout supp 7j 
              find /backup -type d -mtime +7 -exec rm -rf {} +
            volumeMounts:
            - name: backup-storage
              mountPath: /backup
          restartPolicy: Never
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: backup-pvc
